stages:
  - test
  - build

test:
  stage: test
  image: golang:1.17
  script: 
   - go test .

build:
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""

  services:
    - docker:dind

  script:
   - docker build .
